# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Password
      # You must change password, it is set for only training purpose and it is not secure

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080